# Generated by Django 5.0 on 2023-12-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_alter_participant_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='present',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
