# Generated by Django 5.0 on 2023-12-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_participant_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='present',
            field=models.BooleanField(default=False),
        ),
    ]
