# Generated by Django 5.0 on 2023-12-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0005_alter_participant_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nom',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
