# Generated by Django 5.0 on 2023-12-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0006_alter_event_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='couleur_p',
            new_name='couleur_principale',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='couleur_s',
            new_name='couleur_secondaire',
        ),
    ]
