# Generated by Django 5.0 on 2023-12-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0007_rename_couleur_p_event_couleur_principale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lien',
            field=models.CharField(default='a', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
