# Generated by Django 5.0 on 2023-12-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0008_event_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('prenom', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('mdp', models.CharField(max_length=64)),
            ],
        ),
    ]
